#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 15 20:15:15 2020

@author: davideferri
"""

import numpy as np 
import pandas as pd 
import scipy.stats as ss 
import logging 
import pymc3 as pm
import arviz as az

